### ISSUE TITLE
Consider publishing to Open VSX registry

### ISSUE THREAD

**Issue by antcooper** [putyourlightson/vscode-sprig-support#1]
### Is your feature request related to a problem? Please describe.
I use Gitpod for some Craft projects, this relies on the Open VSX registry for extensions rather than the Microsoft Extension Marketplace that can only be accessed from official VS Code products.

### Describe the solution you would like
To publish the Sprig Extension and future updates to the Open VSX registry alongside the Microsoft Extension Marketplace so it can be used with Gitpod and other open source variants of VS Code. There are detail in this [Gitpod blog post](https://www.gitpod.io/blog/open-vsx).

Thanks for your work developing this, and Sprig, Ben!

**Comment by bencroker** [comment]
Sorry, this went under my radar, somehow.

I looked into adding the extension to the Open VSX registry but honestly, I never got past creating two new accounts and signing agreements.

It looks like you may already be able to publish open-source VS Code extensions, as explained here:
https://github.com/open-vsx/publish-extensions/blob/master/DEVELOPMENT.md
